# coding: utf-8

"""
    The First Descendant Metadata API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from meta_client.models.module_response_inner import ModuleResponseInner

class TestModuleResponseInner(unittest.TestCase):
    """ModuleResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModuleResponseInner:
        """Test ModuleResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModuleResponseInner`
        """
        model = ModuleResponseInner()
        if include_optional:
            return ModuleResponseInner(
                module_name = '',
                module_id = '',
                image_url = '',
                module_type = '',
                module_tier = '',
                module_socket_type = '',
                module_class = '',
                module_stat = [
                    meta_client.models.module_response_inner_module_stat_inner.ModuleResponse_inner_module_stat_inner(
                        level = 1.337, 
                        module_capacity = 1.337, 
                        value = '', )
                    ]
            )
        else:
            return ModuleResponseInner(
        )
        """

    def testModuleResponseInner(self):
        """Test ModuleResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
