# coding: utf-8

"""
    The First Descendant Metadata API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from meta_client.models.module_response_inner_module_stat_inner import ModuleResponseInnerModuleStatInner

class TestModuleResponseInnerModuleStatInner(unittest.TestCase):
    """ModuleResponseInnerModuleStatInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModuleResponseInnerModuleStatInner:
        """Test ModuleResponseInnerModuleStatInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModuleResponseInnerModuleStatInner`
        """
        model = ModuleResponseInnerModuleStatInner()
        if include_optional:
            return ModuleResponseInnerModuleStatInner(
                level = 1.337,
                module_capacity = 1.337,
                value = ''
            )
        else:
            return ModuleResponseInnerModuleStatInner(
        )
        """

    def testModuleResponseInnerModuleStatInner(self):
        """Test ModuleResponseInnerModuleStatInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
