# coding: utf-8

"""
    The First Descendant Metadata API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from meta_client.models.error_message_error import ErrorMessageError

class TestErrorMessageError(unittest.TestCase):
    """ErrorMessageError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorMessageError:
        """Test ErrorMessageError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorMessageError`
        """
        model = ErrorMessageError()
        if include_optional:
            return ErrorMessageError(
                name = '',
                message = ''
            )
        else:
            return ErrorMessageError(
        )
        """

    def testErrorMessageError(self):
        """Test ErrorMessageError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
