# coding: utf-8

"""
    The First Descendant User API

    - Game data for The First Descendant becomes available after 10 minutes on average. - Please note that the OUID may change due to game content updates. Be cautious when renewing services based on the OUID. - For the interpretation of various ID values such as those for descendants, weapons, etc., please refer to the separately provided metadata API (/meta/). - Nickname must distinguish between uppercase and lowercase letters.

    The version of the OpenAPI document: 1.0.0
    Contact: help_openapi@nexon.co.kr
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from user_client.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_thefirstdescendant_get_user_basic(self) -> None:
        """Test case for thefirstdescendant_get_user_basic

        Retrieve basic information
        """
        pass

    def test_thefirstdescendant_get_user_descendant(self) -> None:
        """Test case for thefirstdescendant_get_user_descendant

        Retrieve equipped descendant information
        """
        pass

    def test_thefirstdescendant_get_user_external_component(self) -> None:
        """Test case for thefirstdescendant_get_user_external_component

        Retrieve equipped external component information
        """
        pass

    def test_thefirstdescendant_get_user_id(self) -> None:
        """Test case for thefirstdescendant_get_user_id

        Retrieve account identifier (OUID)
        """
        pass

    def test_thefirstdescendant_get_user_reactor(self) -> None:
        """Test case for thefirstdescendant_get_user_reactor

        Retrieve equipped Reactor information
        """
        pass

    def test_thefirstdescendant_get_user_weapon(self) -> None:
        """Test case for thefirstdescendant_get_user_weapon

        Retrieve equipped weapon information
        """
        pass


if __name__ == '__main__':
    unittest.main()
