# coding: utf-8

"""
    The First Descendant Metadata API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from meta_client.api.meta_data_api import MetaDataApi


class TestMetaDataApi(unittest.TestCase):
    """MetaDataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetaDataApi()

    def tearDown(self) -> None:
        pass

    def test_static_tfd_meta_language_code_descendant_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_descendant_json_get

        Retrieve descendant metadata
        """
        pass

    def test_static_tfd_meta_language_code_external_component_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_external_component_json_get

        Retrieve external component metadata
        """
        pass

    def test_static_tfd_meta_language_code_module_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_module_json_get

        Retrieve module metadata
        """
        pass

    def test_static_tfd_meta_language_code_reactor_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_reactor_json_get

        Retrieve Reactor metadata
        """
        pass

    def test_static_tfd_meta_language_code_reward_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_reward_json_get

        Retrieve Difficulty Level Rewards metadata
        """
        pass

    def test_static_tfd_meta_language_code_stat_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_stat_json_get

        Retrieve base stat metadata
        """
        pass

    def test_static_tfd_meta_language_code_title_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_title_json_get

        Retrieve Title metadata
        """
        pass

    def test_static_tfd_meta_language_code_void_battle_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_void_battle_json_get

        Retrieve Void Intercept Battle metadata
        """
        pass

    def test_static_tfd_meta_language_code_weapon_json_get(self) -> None:
        """Test case for static_tfd_meta_language_code_weapon_json_get

        Retrieve weapon metadata
        """
        pass


if __name__ == '__main__':
    unittest.main()
