# coding: utf-8

"""
    The First Descendant Metadata API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from meta_client.models.stat_response_inner import StatResponseInner

class TestStatResponseInner(unittest.TestCase):
    """StatResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatResponseInner:
        """Test StatResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatResponseInner`
        """
        model = StatResponseInner()
        if include_optional:
            return StatResponseInner(
                stat_id = '',
                stat_name = ''
            )
        else:
            return StatResponseInner(
        )
        """

    def testStatResponseInner(self):
        """Test StatResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
