# coding: utf-8

"""
    The First Descendant Module Recommendation API

    - Game data for The First Descendant becomes available after 10 minutes on average. - Please note that the OUID may change due to game content updates. Be cautious when renewing services based on the OUID. - For the interpretation of various ID values such as those for descendants, weapons, etc., please refer to the separately provided metadata API (/meta/). - Recommended modules are provided based on the successful records of Void Intercept Battles. Therefore, if there are insufficient records matching the search criteria, the query responses may be empty.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from recommendation_client.api.recommendation_api import RecommendationApi


class TestRecommendationApi(unittest.TestCase):
    """RecommendationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecommendationApi()

    def tearDown(self) -> None:
        pass

    def test_tfd_v1_recommendation_module_get(self) -> None:
        """Test case for tfd_v1_recommendation_module_get

        Module recommendation
        """
        pass


if __name__ == '__main__':
    unittest.main()
