# coding: utf-8

"""
    The First Descendant User API

    - Game data for The First Descendant becomes available after 10 minutes on average. - Please note that the OUID may change due to game content updates. Be cautious when renewing services based on the OUID. - For the interpretation of various ID values such as those for descendants, weapons, etc., please refer to the separately provided metadata API (/meta/). - Nickname must distinguish between uppercase and lowercase letters.

    The version of the OpenAPI document: 1.0.0
    Contact: help_openapi@nexon.co.kr
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from user_client.models.user_descendant import UserDescendant

class TestUserDescendant(unittest.TestCase):
    """UserDescendant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserDescendant:
        """Test UserDescendant
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserDescendant`
        """
        model = UserDescendant()
        if include_optional:
            return UserDescendant(
                ouid = '',
                user_name = 'Nickname#1234',
                descendant_id = '',
                descendant_slot_id = '',
                descendant_level = 1.337,
                module_max_capacity = 1.337,
                module_capacity = 1.337,
                module = [
                    user_client.models.user_descendant_module_inner.UserDescendant_module_inner(
                        module_slot_id = '', 
                        module_id = '', 
                        module_enchant_level = 1.337, )
                    ]
            )
        else:
            return UserDescendant(
        )
        """

    def testUserDescendant(self):
        """Test UserDescendant"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
