# coding: utf-8

"""
    The First Descendant Metadata API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from meta_client.models.weapon_response_inner import WeaponResponseInner

class TestWeaponResponseInner(unittest.TestCase):
    """WeaponResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WeaponResponseInner:
        """Test WeaponResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WeaponResponseInner`
        """
        model = WeaponResponseInner()
        if include_optional:
            return WeaponResponseInner(
                weapon_name = '',
                weapon_id = '',
                image_url = '',
                weapon_type = '',
                weapon_tier = '',
                weapon_rounds_type = '',
                base_stat = [
                    meta_client.models.weapon_response_inner_base_stat_inner.WeaponResponse_inner_base_stat_inner(
                        stat_id = '', 
                        stat_value = 1.337, )
                    ],
                firearm_atk = [
                    meta_client.models.weapon_response_inner_firearm_atk_inner.WeaponResponse_inner_firearm_atk_inner(
                        level = 1.337, 
                        firearm = [
                            meta_client.models.weapon_response_inner_firearm_atk_inner_firearm_inner.WeaponResponse_inner_firearm_atk_inner_firearm_inner(
                                firearm_atk_type = '', 
                                firearm_atk_value = 1.337, )
                            ], )
                    ],
                weapon_perk_ability_name = '',
                weapon_perk_ability_description = '',
                weapon_perk_ability_image_url = ''
            )
        else:
            return WeaponResponseInner(
        )
        """

    def testWeaponResponseInner(self):
        """Test WeaponResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
