# coding: utf-8

# flake8: noqa

"""
    The First Descendant Module Recommendation API

    - Game data for The First Descendant becomes available after 10 minutes on average. - Please note that the OUID may change due to game content updates. Be cautious when renewing services based on the OUID. - For the interpretation of various ID values such as those for descendants, weapons, etc., please refer to the separately provided metadata API (/meta/). - Recommended modules are provided based on the successful records of Void Intercept Battles. Therefore, if there are insufficient records matching the search criteria, the query responses may be empty.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from recommendation.api.recommendation_api import RecommendationApi

# import ApiClient
from recommendation.api_response import ApiResponse
from recommendation.api_client import ApiClient
from recommendation.configuration import Configuration
from recommendation.exceptions import OpenApiException
from recommendation.exceptions import ApiTypeError
from recommendation.exceptions import ApiValueError
from recommendation.exceptions import ApiKeyError
from recommendation.exceptions import ApiAttributeError
from recommendation.exceptions import ApiException

# import models into sdk package
from recommendation.models.error_message import ErrorMessage
from recommendation.models.error_message_error import ErrorMessageError
from recommendation.models.module_recommendation_response import ModuleRecommendationResponse
from recommendation.models.module_recommendation_response_descendant import ModuleRecommendationResponseDescendant
from recommendation.models.module_recommendation_response_descendant_recommendation_inner import ModuleRecommendationResponseDescendantRecommendationInner
from recommendation.models.module_recommendation_response_weapon import ModuleRecommendationResponseWeapon
