# coding: utf-8

"""
    The First Descendant Metadata API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DescendantResponseInnerDescendantSkillInner(BaseModel):
    """
    DescendantResponseInnerDescendantSkillInner
    """ # noqa: E501
    skill_type: Optional[StrictStr] = Field(default=None, description="Skill type (active/passive)")
    skill_name: Optional[StrictStr] = Field(default=None, description="Skill name")
    element_type: Optional[StrictStr] = Field(default=None, description="Skill type")
    arche_type: Optional[StrictStr] = Field(default=None, description="Arche type")
    skill_image_url: Optional[StrictStr] = Field(default=None, description="Skill icon image path")
    skill_description: Optional[StrictStr] = Field(default=None, description="Skill description")
    __properties: ClassVar[List[str]] = ["skill_type", "skill_name", "element_type", "arche_type", "skill_image_url", "skill_description"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DescendantResponseInnerDescendantSkillInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DescendantResponseInnerDescendantSkillInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "skill_type": obj.get("skill_type"),
            "skill_name": obj.get("skill_name"),
            "element_type": obj.get("element_type"),
            "arche_type": obj.get("arche_type"),
            "skill_image_url": obj.get("skill_image_url"),
            "skill_description": obj.get("skill_description")
        })
        return _obj


