# coding: utf-8

"""
    The First Descendant Metadata API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from meta.models.descendant_response_inner_descendant_skill_inner import DescendantResponseInnerDescendantSkillInner
from meta.models.descendant_response_inner_descendant_stat_inner import DescendantResponseInnerDescendantStatInner
from typing import Optional, Set
from typing_extensions import Self

class DescendantResponseInner(BaseModel):
    """
    DescendantResponseInner
    """ # noqa: E501
    descendant_id: Optional[StrictStr] = Field(default=None, description="Descendant identifier")
    descendant_name: Optional[StrictStr] = Field(default=None, description="Descendant name")
    descendant_image_url: Optional[StrictStr] = Field(default=None, description="Descendant image path")
    descendant_stat: Optional[List[DescendantResponseInnerDescendantStatInner]] = Field(default=None, description="Descendant stat information")
    descendant_skill: Optional[List[DescendantResponseInnerDescendantSkillInner]] = Field(default=None, description="Descendant skill information")
    __properties: ClassVar[List[str]] = ["descendant_id", "descendant_name", "descendant_image_url", "descendant_stat", "descendant_skill"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DescendantResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in descendant_stat (list)
        _items = []
        if self.descendant_stat:
            for _item in self.descendant_stat:
                if _item:
                    _items.append(_item.to_dict())
            _dict['descendant_stat'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in descendant_skill (list)
        _items = []
        if self.descendant_skill:
            for _item in self.descendant_skill:
                if _item:
                    _items.append(_item.to_dict())
            _dict['descendant_skill'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DescendantResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "descendant_id": obj.get("descendant_id"),
            "descendant_name": obj.get("descendant_name"),
            "descendant_image_url": obj.get("descendant_image_url"),
            "descendant_stat": [DescendantResponseInnerDescendantStatInner.from_dict(_item) for _item in obj["descendant_stat"]] if obj.get("descendant_stat") is not None else None,
            "descendant_skill": [DescendantResponseInnerDescendantSkillInner.from_dict(_item) for _item in obj["descendant_skill"]] if obj.get("descendant_skill") is not None else None
        })
        return _obj


