# coding: utf-8

"""
    The First Descendant Metadata API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from meta.models.external_component_response_inner_base_stat_inner import ExternalComponentResponseInnerBaseStatInner
from meta.models.external_component_response_inner_set_option_detail_inner import ExternalComponentResponseInnerSetOptionDetailInner
from typing import Optional, Set
from typing_extensions import Self

class ExternalComponentResponseInner(BaseModel):
    """
    ExternalComponentResponseInner
    """ # noqa: E501
    external_component_id: Optional[StrictStr] = Field(default=None, description="External component identifier")
    external_component_name: Optional[StrictStr] = Field(default=None, description="External component name")
    image_url: Optional[StrictStr] = Field(default=None, description="External component image path")
    external_component_equipment_type: Optional[StrictStr] = Field(default=None, description="External component equipment part")
    external_component_tier: Optional[StrictStr] = Field(default=None, description="External components tier")
    base_stat: Optional[List[ExternalComponentResponseInnerBaseStatInner]] = Field(default=None, description="External component effect by level information")
    set_option_detail: Optional[List[ExternalComponentResponseInnerSetOptionDetailInner]] = Field(default=None, description="External component set option information")
    __properties: ClassVar[List[str]] = ["external_component_id", "external_component_name", "image_url", "external_component_equipment_type", "external_component_tier", "base_stat", "set_option_detail"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalComponentResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in base_stat (list)
        _items = []
        if self.base_stat:
            for _item in self.base_stat:
                if _item:
                    _items.append(_item.to_dict())
            _dict['base_stat'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in set_option_detail (list)
        _items = []
        if self.set_option_detail:
            for _item in self.set_option_detail:
                if _item:
                    _items.append(_item.to_dict())
            _dict['set_option_detail'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalComponentResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "external_component_id": obj.get("external_component_id"),
            "external_component_name": obj.get("external_component_name"),
            "image_url": obj.get("image_url"),
            "external_component_equipment_type": obj.get("external_component_equipment_type"),
            "external_component_tier": obj.get("external_component_tier"),
            "base_stat": [ExternalComponentResponseInnerBaseStatInner.from_dict(_item) for _item in obj["base_stat"]] if obj.get("base_stat") is not None else None,
            "set_option_detail": [ExternalComponentResponseInnerSetOptionDetailInner.from_dict(_item) for _item in obj["set_option_detail"]] if obj.get("set_option_detail") is not None else None
        })
        return _obj


