# coding: utf-8

"""
    The First Descendant Metadata API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from meta.models.module_response_inner_module_stat_inner import ModuleResponseInnerModuleStatInner
from typing import Optional, Set
from typing_extensions import Self

class ModuleResponseInner(BaseModel):
    """
    ModuleResponseInner
    """ # noqa: E501
    module_name: Optional[StrictStr] = Field(default=None, description="Module name")
    module_id: Optional[StrictStr] = Field(default=None, description="Module identifier")
    image_url: Optional[StrictStr] = Field(default=None, description="Module image path")
    module_type: Optional[StrictStr] = Field(default=None, description="Module type")
    module_tier: Optional[StrictStr] = Field(default=None, description="Module tier")
    module_socket_type: Optional[StrictStr] = Field(default=None, description="Module slot socket type")
    module_class: Optional[StrictStr] = Field(default=None, description="Module class")
    module_stat: Optional[List[ModuleResponseInnerModuleStatInner]] = Field(default=None, description="Module attribute information")
    __properties: ClassVar[List[str]] = ["module_name", "module_id", "image_url", "module_type", "module_tier", "module_socket_type", "module_class", "module_stat"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModuleResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in module_stat (list)
        _items = []
        if self.module_stat:
            for _item in self.module_stat:
                if _item:
                    _items.append(_item.to_dict())
            _dict['module_stat'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModuleResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "module_name": obj.get("module_name"),
            "module_id": obj.get("module_id"),
            "image_url": obj.get("image_url"),
            "module_type": obj.get("module_type"),
            "module_tier": obj.get("module_tier"),
            "module_socket_type": obj.get("module_socket_type"),
            "module_class": obj.get("module_class"),
            "module_stat": [ModuleResponseInnerModuleStatInner.from_dict(_item) for _item in obj["module_stat"]] if obj.get("module_stat") is not None else None
        })
        return _obj


